# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: Build maven app
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
- task: Docker@2
  displayName: Build Docker image from Dockerfile
  inputs:
    containerRegistry: 'blueharvest-registry'
    repository: 'my-repo'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: Push Docker Image to Azure Container Registry
  inputs:
    containerRegistry: 'blueharvest-registry'
    repository: 'my-repo'
    command: 'push'

    

